---
title: "04_analyse_results"
author: "Nils Hellwig"
date: "6/14/2023"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r}
top_n <- 1
```


```{r}
evaluation_results <- read.csv("results_rf.csv")

evaluation_results <- evaluation_results %>%
  mutate_at(vars(names(evaluation_results)), as.numeric)

evaluation_results <- evaluation_results %>%
  mutate(year_month = paste(year_start_test, month_start_test, sep = "-"))


evaluation_results
```


```{r}
feature_columns <- evaluation_results[, 11:ncol(evaluation_results)]
once_listed_top_n_features <- vector("character")

for (i in 1:nrow(feature_columns)) {
  row_values <- unlist(feature_columns[i, ]) # i got an "cannot xtfrm data frames" error so i converted the row to a vector using unlist because sort can only handle vectors
  sorted_values <- sort(row_values, decreasing = TRUE)
  
  # get top n features
  top_names <- names(row_values)[match(sorted_values[1:top_n], row_values)]
  once_listed_top_n_features <- c(once_listed_top_n_features, top_names)
}

# remove doublicates
once_listed_top_n_features <- unique(once_listed_top_n_features)
once_listed_top_n_features
```

```{r}
selected_feature_timeseries <- evaluation_results %>%
  select(departure_scheduled_hour_local, year_month)
selected_feature_timeseries
```

```{r, fig.width = 10, fig.height= 3}
selected_feature_timeseries <- evaluation_results %>%
  select(all_of(once_listed_top_n_features), year_month)

selected_feature_timeseries <- tidyr::gather(selected_feature_timeseries, key = "feature", value = "importance", -year_month)
selected_feature_timeseries$year_month <- as.Date(paste0(selected_feature_timeseries$year_month, "-01"))

x_labels <- unique(selected_feature_timeseries$year_month)

for (year in unique(year(selected_feature_timeseries$year_month))) {
  year_data <- subset(selected_feature_timeseries, year(selected_feature_timeseries$year_month) == year)
  plot <- ggplot(year_data, aes(x = year_month, y = importance, color = feature)) +
    geom_line() +
    labs(x = "Month", y = "Variable Importance", color = "Feature") +
    scale_x_date(breaks = x_labels, labels = format(x_labels, "%b %Y")) +
    theme_minimal() +
    ggtitle(paste("Year", year))

  print(plot)  # oder ggsave(filename) zum Speichern des Plots als Bild
}
```

```{r}
selected_feature_timeseries
```



