---
title: "Predict Departure Delay"
author: "Nils Hellwig"
date: "24 5 2023"
output: html_document
---

# Load Packages

```{r}
library(ggplot2)
library(dplyr)
library(stringr)
library(caret)
library(e1071)
```

# Load Datasets

First, we need to load the dataset and add some columns that will be used for feature extraction (as already known from the data exploration script).

```{r}
# Load departure data
departure_data <- read.csv("../datasets/departure_dataset.csv")
weather_data <- read.csv("../datasets/weather_munich_dataset.csv")
departure_data
```

```{r}
departure_data$departure_scheduled_datetime_local <- as.POSIXct(departure_data$departure_scheduled_datetime_local)
weather_data$six_hours_starting_from_datatime <- as.POSIXct(paste(weather_data$date, weather_data$six_hours_starting_from))
```

```{r}
get_weather_data <- function(departure_time) {
  if (format(departure_time, format = "%Y-%m-%d 06:00:00") > departure_time) {
    weather_span <- format(departure_time, format = "%Y-%m-%d 00:00:00")
  } else if (format(departure_time, format = "%Y-%m-%d 12:00:00") > departure_time) {
    weather_span <- format(departure_time, format = "%Y-%m-%d 06:00:00")
  } else if (format(departure_time, format = "%Y-%m-%d 18:00:00") > departure_time) {
    weather_span <- format(departure_time, format = "%Y-%m-%d 12:00:00")
  } else if (format(departure_time, format = "%Y-%m-%d 24:00:00") > departure_time) {
    weather_span <- format(departure_time, format = "%Y-%m-%d 18:00:00")
  } 
  nearest_row <- weather_data[weather_data$six_hours_starting_from_datatime == weather_span,]
  return(weather_span)
}

departure_data$six_hours_starting_from_datatime <- as.POSIXct(sapply(departure_data$departure_scheduled_datetime_local, get_weather_data))
# exclude unnecessary columns that we don't want to add to the departure_data dataframe
merge_cols_weather_data <- setdiff(names(weather_data), c("date", "six_hours_starting_from"))
departure_data <- merge(departure_data, weather_data[, c(merge_cols_weather_data)], by.x = "six_hours_starting_from_datatime", by.y = "six_hours_starting_from_datatime", all.x = TRUE)
# For a better understanding of what data is in this column
departure_data <- departure_data %>%
  rename(weather_description = description)

# There are cases where no weather description is given but other weather data such as temperature is available. 
# In this case, I set a value for these cases so that the value is not NA but such cases get their own column for the one-hot encoding.
departure_data$weather_description <- ifelse(is.na(departure_data$weather_description), "Notspecified", departure_data$weather_description)

# Since there should be a separate column for each value for weather_description later, which then has its value as the column name, I remove all "." and spaces so that you can access the column name later using $ in R.
departure_data$weather_description <- gsub("[. ]", "", departure_data$weather_description)
departure_data$airline_name <- gsub("[. ]", "", departure_data$airline_name)
departure_data$destination_IATA <- gsub("[. ]", "", departure_data$destination_IATA)
departure_data
```

As I want to predict the amount of delay, I will only look at flights that have landed

```{r}
departure_data <- departure_data[departure_data$flight_status == "Landed", ]
departure_data
```

# ------ Feature Coding --------

```{r}
dataset <- departure_data %>%
  select(departure_scheduled_datetime_local,
         delay_departure_min,
         departure_scheduled_weekday_local,
         departure_scheduled_hour_local, # continuous variable
         departure_scheduled_month_local, # continuous variable 
         departure_scheduled_year_local, # continuous variable
         temperature_celsius)
```

```{r}
dataset$departure_scheduled_weekday_local <- as.integer(factor(dataset$departure_scheduled_weekday_local,
                                                                      levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"),
                                                                      labels = 1:7))
dataset
```

```{r}
# One-Hot Encoding for categorical variables
# If MARGIN = 2 is set, this means that the function iterates over the columns of the matrix.
dataset <- cbind(dataset, apply(model.matrix(~ weather_description - 1, data = departure_data), 2, as.integer)) 
dataset <- cbind(dataset, apply(model.matrix(~ airline_name - 1, data = departure_data), 2, as.integer))
dataset <- cbind(dataset, apply(model.matrix(~ destination_IATA - 1, data = departure_data), 2, as.integer))
dataset
```

Remove Outliers

```{r}
z_scores <- scale(dataset$delay_departure_min)
z_threshold <- 3
outliers_train_df <- abs(z_scores) > z_threshold
dataset <- dataset[!outliers_train_df, ]
```

```{r}
dataset[order(dataset$departure_scheduled_datetime_local), ]
```

```{r}
dataset <- dataset %>%
  filter(!(departure_scheduled_year_local == 2017 & departure_scheduled_month_local == 9)) %>%
  filter(!(departure_scheduled_year_local == 2023 & departure_scheduled_month_local == 5))
```


```{r}
year_month_pairs <- dataset %>%
  group_by(departure_scheduled_month_local, departure_scheduled_year_local) %>%
  summarise(average_delay = mean(delay_departure_min)) %>%
  arrange(departure_scheduled_year_local, departure_scheduled_month_local)
year_month_pairs
```

Define Classes

```{r}
category_names_quantiles <- c("earlier, on time or very short delay", "long delay")
category_quantiles <- quantile(dataset$delay_departure_min, probs = c(0.0, 0.5, 1.0))
category_quantiles
```

# ------ Split Dataset to train/test --------

```{r}
set.seed(42)
```


```{r}
train_model <- function () {
  ctrl <- trainControl(verboseIter = TRUE, method="none")
  filtered_train_df <- train_df[-(which(names(train_df) %in% c("departure_scheduled_datetime_local", "delay_departure_min")))]
  filtered_train_df$delay_departure_min_category <- as.character(filtered_train_df$delay_departure_min_category)

  model <- train(delay_departure_min_category ~ .,
         data = filtered_train_df,
         method = "rf", 
         trControl = ctrl,
         )
  return(model)
}
```

```{r}
results_df <- data.frame()
```

```{r}
evaluate_model <- function () {
  filtered_test_df <- test_df
  filtered_test_df$delay_departure_min_category <- droplevels(filtered_test_df$delay_departure_min_category)
  predictions <- predict(model, newdata = filtered_test_df)

  cf <- confusionMatrix(predictions, filtered_test_df$delay_departure_min_category)
  feature_importance <- varImp(model, scale=FALSE)
  print(feature_importance)
  
  feature_importance_row <- feature_importance$importance %>% 
    mutate(names=row.names(.)) %>%
    arrange(names) %>%
    t() %>%
    as.data.frame()

  new_row <- c(year_start_test = year_start_test, month_start_test=month_start_test, cf$overall, as.character(unlist(feature_importance_row["Overall", ]))) 
  results_df <- rbind(results_df, new_row)
  colnames(results_df) <- c("year_start_test", "month_start_test", names(cf$overall), colnames(feature_importance_row))
  return(results_df)
}
```

```{r}
#evaluate_model()
```

```{r}
#for (i in seq(1, nrow(year_month_pairs) - 1)) {
for (i in seq(1, 40)) {
  year_start_train <- year_month_pairs$departure_scheduled_year_local[[i]]
  year_start_test <- year_month_pairs$departure_scheduled_year_local[[i+1]]
  month_start_train <- year_month_pairs$departure_scheduled_month_local[[i]]
  month_start_test <- year_month_pairs$departure_scheduled_month_local[[i+1]]
  
  train_df <- dataset %>%
    filter(departure_scheduled_year_local == year_start_train & departure_scheduled_month_local == month_start_train)
  test_df <- dataset %>%
    filter(departure_scheduled_year_local == year_start_test & departure_scheduled_month_local == month_start_test)
  
  # Add Labels
  train_df$delay_departure_min_category <- cut(train_df$delay_departure_min, 
                                             breaks = category_quantiles, 
                                             labels = category_names_quantiles,
                                             include.lowest = TRUE)
  
  test_df$delay_departure_min_category <- cut(test_df$delay_departure_min, 
                                             breaks = category_quantiles, 
                                             labels = category_names_quantiles,
                                             include.lowest = TRUE) 
  
  # Replace NA with average temeperature
  average_temperature_train <- mean(train_df$temperature_celsius, na.rm = TRUE)
  average_temperature_test <- mean(test_df$temperature_celsius, na.rm = TRUE)
  train_df$temperature_celsius <- ifelse(is.na(train_df$temperature_celsius), average_temperature_train, train_df$temperature_celsius)
  test_df$temperature_celsius <- ifelse(is.na(test_df$temperature_celsius), average_temperature_test, test_df$temperature_celsius)
  
  model <- train_model()
  results_df <- evaluate_model()
}
```

```{r}
results_df
```

