---
title: "02 Preprocess Flight History"
author: "Nils Hellwig"
date: "5/16/2023"
output: html_document
---

## Load Packages

```{r}
library(rvest)
library(tidyverse)
library(stringr)
library(xml2)
source("date_string_formatter.R")
library(lubridate)
```

## Define Settings

```{r}
folder_path_departures <- "datasets/raw_departures_dataset"
```

## Preprocessing of departure flights

```{r}
# Load the filepaths of all the .html-documents
html_documents <- list.files(path = folder_path_departures, pattern = "\\.html$", full.names = TRUE)
html_documents <- tail(html_documents, 5)
head(html_documents)
```

```{r}
departure_data <- data.frame(
  departure_scheduled_datetime_local = character(),
  departure_scheduled_time_local_timezone = character(),
  departure_scheduled_datetime_utc = character(),
  flight_status = character(),
  airline_name = character(),
  flight_number = character(),
  flight_number_IATA = character(),
  airline_code = character(),
  airline_code_IATA = character(),
  airline_country = character(),
  destination_country = character(),
  destination_name = character(),
  destination_IATA = character(),
  destination_ICAO = character(),
  departure_actual_time = character(),
  departure_actual_time_timezone = character(),
  delay_departure_min = numeric(),
  delay_arrival_min = numeric(),
  actual_arrival_time = character(),
  actual_arrival_time_timezone = character(),
  flight_duration_time_min = numeric()
)
```

```{r}
# Load each .html-document and
for (i in seq_along(html_documents)) {
  doc_path <- html_documents[i]
  doc <- read_html(doc_path)
  
  extracted_data <- doc %>%
    html_nodes("tbody tr.bg-gray-50, tbody tr.bg-white")
  
  for (flight_element in extracted_data) {
      # let's start by storing all child elements of a flight's flight_element 
      child_elements_txt <- flight_element %>%
        html_children() %>%
        html_text() %>%
        trimws() # remove whitespaces
      
      flag_imgs <- flight_element %>%
         html_nodes("img[alt*='Flag for']")
      
      if (length(flag_imgs) == 3) {
        print(flag_imgs)
      }

      # It happens that the airline can not be assigned to a country so that there's no flag icon.
      # Example: Flight to Liege (Belgium), see here: https://www.flightera.net/en/airport/Munich/EDDM/departure/2017-12-13%2022_00?
      if (length(flag_imgs) == 1) {
         airline_country <- NULL
         destination_country <- str_extract(html_attr(flag_imgs[1], "alt"), "(?<=Flag for ).*")
      } else {
         airline_country <- str_extract(html_attr(flag_imgs[1], "alt"), "(?<=Flag for ).*")
         destination_country <- str_extract(html_attr(flag_imgs[2], "alt"), "(?<=Flag for ).*")
      }
     
      # There are either one or two flight numbers. The flight number is located before the first two \n\n inside child_elements_txt[2]
      flight_number <- gsub("\\n\\n.*", "", child_elements_txt[2])
      flight_number <- str_extract_all(flight_number, "[A-Z\\d]+")
      
      airline <- strsplit(child_elements_txt[2], "\n")[[1]]
      airline <- tail(airline, n = 1)
    
      airline <- strsplit(airline, "/")[[1]]
      airline_code <- tail(strsplit(airline[1], " ")[[1]], n = 1)
      airline_code_IATA <- airline[2]
      airline_name <- sub("\\s\\S+$", "", airline)[1]
      
      departure_scheduled_date_local <- convert_date_string(strsplit(child_elements_txt[1], "\n")[[1]][1])
      flight_status <- tail(gsub("\\s+", "",strsplit(child_elements_txt[1], "\n")[[1]]), n = 1)
      
      # Although we know that the local timezone of munich is CEST, I decided to extract that data too because 
      # one might want to use the script for another airport
      if (year(as.Date(departure_scheduled_date_local))==2023) {
        departure_scheduled_time_local <- strsplit(child_elements_txt[1], "\n")[[1]][7]
        departure_scheduled_time_local_timezone <- strsplit(child_elements_txt[1], "\n")[[1]][8]
      } else {
        departure_scheduled_time_local <- strsplit(child_elements_txt[1], "\n")[[1]][8]
        departure_scheduled_time_local_timezone <- strsplit(child_elements_txt[1], "\n")[[1]][9]
      }

      departure_scheduled_datetime_local <- paste(departure_scheduled_date_local, departure_scheduled_time_local)
      departure_scheduled_datetime_utc <- format(with_tz(ymd_hm(departure_scheduled_datetime_local, tz = "CEST"), "UTC"), "%Y-%m-%d %H:%M")
     
      destination_name <- sub(" \\(.*", "", child_elements_txt[3])
      # str_match returns the second column of these matrices
      flight_code_IATA <- str_match(child_elements_txt[3], "\\(([A-Z]{3}) /")[, 2]
      flight_code_ICAO <- str_match(child_elements_txt[3], " / ([A-Z]{4})\\)")[, 2]
      
      if (flight_status != "Cancelled" & flight_status != "Diverted" & flight_status != "Unknown") {
        departure_actual_time <- sub("\\n.*", "", child_elements_txt[5])
        departure_actual_time_timezone <- strsplit(child_elements_txt[5], "\n")[[1]][2]
      
        delay_departure_split <- strsplit(child_elements_txt[5], "\n")[[1]]
        delay_departure_min <- extract_minutes_from_delay_string(delay_departure_split)
      
        delay_arrival_split <- strsplit(child_elements_txt[6], "\n")[[1]]
        delay_arrival_min <- extract_minutes_from_delay_string(delay_arrival_split)
      
        actual_arrival_time <- sub("\\n.*", "", child_elements_txt[6])
        actual_arrival_time_timezone <- strsplit(child_elements_txt[6], "\n")[[1]][2]
      
        flight_duration_time_min <- extract_minutes_from_delay_string(child_elements_txt[7])
      }
      
      flight_number_IATA <- flight_number[[1]][2]
      flight_number <- flight_number[[1]][1]
      
      # Finally, we can add all the extracted information regarding a specific flight to our dataframe
      departure_data <- departure_data %>%
        add_row(
          departure_scheduled_datetime_local = departure_scheduled_datetime_local,
          departure_scheduled_time_local_timezone = departure_scheduled_time_local_timezone,
          departure_scheduled_datetime_utc = departure_scheduled_datetime_utc,
          airline_code = airline_code,
          airline_code_IATA = airline_code_IATA,
          airline_name = airline_name,
          airline_country = airline_country,
          flight_number = flight_number[[1]][1],
          flight_number_IATA = flight_number_IATA,
          flight_status = flight_status,
          departure_actual_time = departure_actual_time,
          departure_actual_time_timezone = departure_actual_time_timezone,
          destination_name = destination_name,
          destination_IATA = flight_code_IATA,
          destination_ICAO = flight_code_ICAO,
          destination_country = destination_country,
          delay_departure_min = delay_departure_min,
          delay_arrival_min = delay_arrival_min,
          actual_arrival_time = actual_arrival_time,
          actual_arrival_time_timezone = actual_arrival_time_timezone,
          flight_duration_time_min = flight_duration_time_min
        )
  }
}
```

```{r}
duplicate_rows <- departure_data[duplicated(departure_data), ]
departure_data <- distinct(departure_data)
```

```{r}
departure_data
```


```{r}
#write.csv(departure_data, file = "datasets/departure_dataset.csv", row.names = FALSE)
```
