---
title: "Predict Departure"
author: "Nils Hellwig"
date: "5/29/2023"
output: html_document
---

```{r}
# Beispieldaten erstellen
x <- c(1, 2, 3, 4, 5)  # Unabhängige Variable
y <- c(2, 4, 5, 4, 5)  # Abhängige Variable

# Lineare Regression durchführen
regression <- lm(y ~ x)

# Ergebnisse anzeigen
summary(regression)

plot(x, y, main = "Lineare Regression", xlab = "x", ylab = "y")
abline(regression, col = "red")
```

```{r}
# Beispieldaten erstellen
x1 <- c(1, 2, 3, 4, 5, 6)  # Erste unabhängige Variable
x2 <- c(2, 4, 5, 3, 1, 7)  # Zweite unabhängige Variable
y <- c(3, 6, 8, 5, 2, 8)   # Abhängige Variable

# Multiple lineare Regression durchführen
regression <- lm(y ~ x1 + x2)

# Zusammenfassung der Ergebnisse anzeigen
summary(regression)

# Erklärungen:
# Residual = beobachteter Wert (y) - vorhergesagter Wert (y^)
# 1.7208 -> Wert von y, wenn x1/x2 null sind
# -0.1753 -> wenn x1 sich um eine Einheit (+1) ändert, wie ändert sich dann y
# -1.1526 -> wenn x1 sich um eine Einheit (+1) ändert, wie ändert sich dann y

# Std Error (Intercept): der geschätzte Wert für das Intercept (Schnittpunkt mit der y-Achse) von 1.7208 im Durchschnitt um 0.9889 Einheiten nach oben oder unten abweichen kann.
# x1/x2: In einfacher Sprache bedeutet der Standardfehler, wie genau oder ungenau die Schätzung des Koeffizienten ist. Ein niedrigerer Standardfehler bedeutet, dass die Schätzung des Koeffizienten genauer ist, während ein höherer Standardfehler auf eine größere Unsicherheit in der Schätzung hinweist.

```

```{r}
library(e1071)

# Datenpunkte
x <- c(1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 21, 22)
y <- c(3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45)

# Datenmatrix erstellen
data <- data.frame(x = x, y = y)

# SVM-Modell erstellen
svm_model <- svm(y ~ ., data = data, kernel = "polynomial", C=0.001)

# Vorhersagen treffen
new_data <- data.frame(x = c(1, 2, 4, 5))
predictions <- predict(svm_model, newdata = new_data)

predictions
```

```{r}
library(neuralnet)

# Daten definieren
x <- c(1:50)
y <- c(11:60)

# Daten in ein Dataframe konvertieren
data <- data.frame(x, y)

# Neuronales Netzwerk definieren und Anzahl der Epochen festlegen
net <- neuralnet(y ~ x, data = data, hidden = c(256, 256, 128), linear.output = TRUE, rep=2)

# Neue Werte für x definieren, für die Sie y vorhersagen möchten
new_x <- data.frame(x = c(51:60))

# Vorhersagen für y basierend auf neuen x-Werten
predictions <- compute(net, new_x)

# Vorhersagewerte anzeigen
predicted_y <- predictions$net.result
predicted_y

```

```{r}
# Beispiel-Temperaturdaten
temperatur <- c(20, 25, 30, 15, 10, 35)

# Funktion zur Min-Max-Skalierung
min_max_scale <- function(x) {
  (x - min(temperatur)) / (max(temperatur) - min(temperatur))
}

# Temperaturdaten skalieren
temperatur_scaled <- min_max_scale(temperatur)

# Neue Werte skalieren
neue_temperatur <- c(20, 40)
neue_temperatur_scaled <- min_max_scale(neue_temperatur)

# Ergebnisse anzeigen
temperatur_scaled
neue_temperatur_scaled

```

```{r}
x1 <- c(1:1000)  # Erste unabhängige Variable
x2 <- c(1001:2000)  # Zweite unabhängige Variable
y <- c(3001:4000)   # Abhängige Variable

# Multiple lineare Regression durchführen
regression <- lm(y ~ x1 + x2)

# Zusammenfassung der Ergebnisse anzeigen
summary(regression)

```

